# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/base_system_ila_0_0.xci
# IP: The module: 'base_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/bd_e763.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763 || ORIG_REF_NAME==bd_e763} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_1/bd_e763_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_g_inst_0 || ORIG_REF_NAME==bd_e763_g_inst_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/bd_e763_ooc.xdc

# IP: Z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/base_system_ila_0_0.xci
# IP: The module: 'base_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/bd_e763.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763 || ORIG_REF_NAME==bd_e763} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_1/bd_e763_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_g_inst_0 || ORIG_REF_NAME==bd_e763_g_inst_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/bd_e763_ooc.xdc
