# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_0_0/base_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_1_0/base_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] -quiet

# IP: bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==base_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_0/base_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_0 || ORIG_REF_NAME==base_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_0/bd_0/bd_e763.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763 || ORIG_REF_NAME==bd_e763} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_1/bd_e763_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e763_g_inst_0 || ORIG_REF_NAME==bd_e763_g_inst_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tc_0_0/base_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tc_0_0 || ORIG_REF_NAME==base_v_tc_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_1 || ORIG_REF_NAME==base_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_0/base_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_0 || ORIG_REF_NAME==base_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_0/base_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_0 || ORIG_REF_NAME==base_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/base/ip/base_smartconnect_0_0/bd_0/bd_b441.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_10/bd_b441_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_16/bd_b441_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_20/bd_b441_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_26/bd_b441_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_21/bd_b441_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_22/bd_b441_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_23/bd_b441_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_24/bd_b441_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_25/bd_b441_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_17/bd_b441_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_18/bd_b441_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_19/bd_b441_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_13/bd_b441_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_14/bd_b441_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_15/bd_b441_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_11/bd_b441_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_12/bd_b441_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_7/bd_b441_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_8/bd_b441_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_9/bd_b441_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_2/bd_b441_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_3/bd_b441_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_4/bd_b441_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_0/bd_b441_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pclk_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tpg_0_0/base_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tpg_0_0 || ORIG_REF_NAME==base_v_tpg_0_0} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_1/base_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_1 || ORIG_REF_NAME==base_system_ila_0_1} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_1/bd_0/bd_27a2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_27a2 || ORIG_REF_NAME==bd_27a2} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/bd_27a2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_2/base_system_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_2 || ORIG_REF_NAME==base_system_ila_0_2} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2 || ORIG_REF_NAME==bd_26e2} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_0_0/base_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconstant_0_0 || ORIG_REF_NAME==base_xlconstant_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tc_0_1/base_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tc_0_1 || ORIG_REF_NAME==base_v_tc_0_1} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_3/base_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_3 || ORIG_REF_NAME==base_system_ila_0_3} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_3/bd_0/bd_e623.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623 || ORIG_REF_NAME==bd_e623} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# XDC: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_ooc.xdc

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_ooc.xdc

# XDC: bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==base_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e763_ila_lib_0 || ORIG_REF_NAME==bd_e763_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_0/bd_0/bd_e763_ooc.xdc

# XDC: bd/base/ip/base_v_tc_0_0/base_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_v_tc_0_0 || ORIG_REF_NAME==base_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_1 || ORIG_REF_NAME==base_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_1 || ORIG_REF_NAME==base_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_10/bd_b441_s00a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_16/bd_b441_s01a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_20/bd_b441_m00s2a_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_21/bd_b441_m00arn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_22/bd_b441_m00rn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_23/bd_b441_m00awn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_24/bd_b441_m00wn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_25/bd_b441_m00bn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_17/bd_b441_sawn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_18/bd_b441_swn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_19/bd_b441_sbn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_11/bd_b441_sarn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_12/bd_b441_srn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_2/bd_b441_arsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_3/bd_b441_rsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_4/bd_b441_awsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_wsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_bsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/base/ip/base_smartconnect_0_0/ooc.xdc

# XDC: bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_v_tpg_0_0/base_v_tpg_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_v_tpg_0_0 || ORIG_REF_NAME==base_v_tpg_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/bd_27a2_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/bd_27a2_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2_ooc.xdc

# XDC: bd/base/ip/base_v_tc_0_1/base_v_tc_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_v_tc_0_1 || ORIG_REF_NAME==base_v_tc_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/bd_e623_ooc.xdc

# XDC: bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc

# XDC: bd/base/base_ooc.xdc
