# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/base_system_ila_0_3.xci
# IP: The module: 'base_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/bd_e623.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623 || ORIG_REF_NAME==bd_e623} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/bd_e623_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/base_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/base_system_ila_0_3.xci
# IP: The module: 'base_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/bd_e623.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623 || ORIG_REF_NAME==bd_e623} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/bd_0/bd_e623_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-wxga/hdmi-wxga.srcs/sources_1/bd/base/ip/base_system_ila_0_3/base_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
