# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_0_0/base_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_1_0/base_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_1/base_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_1 || ORIG_REF_NAME==base_system_ila_0_1} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_1/bd_0/bd_27a2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_27a2 || ORIG_REF_NAME==bd_27a2} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/bd_27a2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_3/base_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_3 || ORIG_REF_NAME==base_system_ila_0_3} -quiet] -quiet

# Block Designs: bd/base/ip/base_system_ila_0_3/bd_0/bd_e623.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623 || ORIG_REF_NAME==bd_e623} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] -quiet

# XDC: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_ooc.xdc

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_ooc.xdc

# XDC: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27a2_ila_lib_0 || ORIG_REF_NAME==bd_27a2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/bd_27a2_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_1/bd_0/bd_27a2_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e623_ila_lib_0 || ORIG_REF_NAME==bd_e623_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/ip/ip_0/bd_e623_ila_lib_0_ooc.xdc

# XDC: bd/base/ip/base_system_ila_0_3/bd_0/bd_e623_ooc.xdc

# XDC: bd/base/base_ooc.xdc
