# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_0_0/base_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_0_0 || ORIG_REF_NAME==base_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gmii_to_rgmii_1_0/base_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gmii_to_rgmii_1_0 || ORIG_REF_NAME==base_gmii_to_rgmii_1_0} -quiet] -quiet

# IP: bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==base_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_2 || ORIG_REF_NAME==base_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_0/base_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_0 || ORIG_REF_NAME==base_system_ila_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tc_0_0/base_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tc_0_0 || ORIG_REF_NAME==base_v_tc_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_1 || ORIG_REF_NAME==base_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_0/base_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_0 || ORIG_REF_NAME==base_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_0/base_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_0 || ORIG_REF_NAME==base_smartconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pclk_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tpg_0_0/base_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tpg_0_0 || ORIG_REF_NAME==base_v_tpg_0_0} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_1/base_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_1 || ORIG_REF_NAME==base_system_ila_0_1} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_2/base_system_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_2 || ORIG_REF_NAME==base_system_ila_0_2} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_0_0/base_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconstant_0_0 || ORIG_REF_NAME==base_xlconstant_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_tc_0_1/base_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_tc_0_1 || ORIG_REF_NAME==base_v_tc_0_1} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_0_1/base_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_1 || ORIG_REF_NAME==base_clk_wiz_0_1} -quiet] -quiet

# IP: bd/base/ip/base_system_ila_0_3/base_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_ila_0_3 || ORIG_REF_NAME==base_system_ila_0_3} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
