# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xci
# IP: The module: 'base_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xci
# IP: The module: 'base_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher_4.0_testing/piSmasher_4.0/piSmasher_4.0.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
