# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.cache/wt [current_project]
set_property parent.project_path Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/hdl/base_wrapper.v
add_files Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/base.bd
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_0_0/synth/base_gmii_to_rgmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_gmii_to_rgmii_1_0/synth/base_gmii_to_rgmii_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_2/base_proc_sys_reset_0_2.xdc]
set_property used_in_synthesis false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/ip/ip_0/bd_e763_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_0/bd_0/bd_e763_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_tc_0_0/base_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_tc_0_0/base_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_0_1/base_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_10/bd_b441_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_16/bd_b441_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_20/bd_b441_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_21/bd_b441_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_22/bd_b441_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_23/bd_b441_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_24/bd_b441_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_25/bd_b441_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_17/bd_b441_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_18/bd_b441_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_19/bd_b441_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_11/bd_b441_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_12/bd_b441_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_2/bd_b441_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_3/bd_b441_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_4/bd_b441_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_proc_sys_reset_pclk_0/base_proc_sys_reset_pclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_tpg_0_0/base_v_tpg_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/bd_0/ip/ip_0/bd_27a2_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/bd_0/bd_27a2_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_1/base_system_ila_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/base_system_ila_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_tc_0_1/base_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_v_tc_0_1/base_v_tc_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/base_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top base_wrapper -part xc7z020clg400-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef base_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file base_wrapper_utilization_synth.rpt -pb base_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
