# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/base_system_ila_0_2.xci
# IP: The module: 'base_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2 || ORIG_REF_NAME==bd_26e2} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/base_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: Z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/base_system_ila_0_2.xci
# IP: The module: 'base_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2 || ORIG_REF_NAME==bd_26e2} -quiet] -quiet

# IP: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_26e2_ila_lib_0 || ORIG_REF_NAME==bd_26e2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/ip/ip_0/bd_26e2_ila_lib_0_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/bd_0/bd_26e2_ooc.xdc

# XDC: z:/Projects/piSmasher/piSmasher-testing/hdmi-720p/hdmi-720p.srcs/sources_1/bd/base/ip/base_system_ila_0_2/base_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
